In [3]:
#ex7.3 Element-wise array multiplication
#Create a 3x3 array containing the even integers from 2 through 18. Create a second 3x3 array containing the integers from 9 to 1. Multiply them.

import numpy as np

a1 = np.array([x for x in range(1, 19) if x%2 == 0])
a2 = np.arange(9, 0, -1)

a1 * a2

array([18, 32, 42, 48, 50, 48, 42, 32, 18])

In [6]:
#ex7.5 Flattening arrays (flatten v ravel methods)
#Create a 2x3 array containing the first 6 powers of 2. Flaten the array with flatten and then ravel. Display the result and the original array.

import numpy as np

a1 = np.array([2**x for x in range(6)]).reshape(2,3)

f1 = a1.flatten()
r1 = a1.ravel()

print('flatten')
print(a1)
print(f1)

print('\nravel')
print(a1)
print(r1)

flatten
[[ 1  2  4]
 [ 8 16 32]]
[ 1  2  4  8 16 32]

ravel
[[ 1  2  4]
 [ 8 16 32]]
[ 1  2  4  8 16 32]


In [4]:
#ex7.6 Research array method astype
#Use linspace and reshape to create a 2*3 array with values 1.1, 2.2, ... 6.6, then use astype to convert the array to an array of integers
import numpy as np

a1 = np.linspace(1.1, 6.6, 6).reshape(2, 3)
print(a1)

a1 = a1.astype(int)
print(a1)

[[1.1 2.2 3.3]
 [4.4 5.5 6.6]]
[[1 2 3]
 [4 5 6]]


In [25]:
#ex7.7 Challenge project: reimplement NumPy array Output
#write a function that reimplements NumPy’s array formatting for two-dimensional arrays using loops. Assume the array contains only positive integer values.
#(NumPy outputs two-dimensional arrays in a nice column-based format that right-aligns every element in a field width.
#The field width’s size is determined by the array element value that requires the most character positions to display.)

def nparray(int_from, int_to, nrow, ncol):
    x = [i for i in range(int_from, int_to)]
    maxwidth = len(str(max(x)))
    for r in range(nrow):
        for c in range(ncol):
            print(f'{x[r*ncol + c]:>{maxwidth}}', end = ' ')
        print('')
                


nparray(0, 12, 3, 4)

 0  1  2  3 
 4  5  6  7 
 8  9 10 11 


In [43]:
#ex7.7 Challenge project: reimplement DataFrame Output
#write a function that reimplements pandas DataFrame formatting using loops. Assume the DataFrame contains only positive integer values and row and column names are ints beginning wtih 0.
#(pandas displays DataFrames in a nice column-based format with row and column labels that right-aligns every element in a column based on the columns widest value.)

def pddf(vals, nrows, ncols):
    #get max width of values in vals for formatting:
    maxwidth = len(str(max(vals)))
    #print column labels
    print(' '*maxwidth, end = ' ')
    for col in range(ncols):
        print(f'{col:>{maxwidth}}', end = ' ')
    print() #print a new line after the col labels
    #print row values preceded by row label
    for row in range(nrows):
        print(f'{row:>{maxwidth}}', end = ' ')
        for col in range(ncols):
            print(f'{vals[row*ncols + col]:>{maxwidth}}', end = ' ')
        print()


pddf([i for i in range(99, 111)], 3, 4)

      0   1   2   3 
  0  99 100 101 102 
  1 103 104 105 106 
  2 107 108 109 110 


In [65]:
#ex7.9 (Indexing and Slicing arrays) 
#Create an array containing the values 1–15, reshape it into a 3-by-5 array, then use indexing and slicing techniques to perform each of the following operations

import numpy as np

x = np.arange(1, 16).reshape(3, 5)
print(x)

#1. seelct row 2
print(f'1. {x[2, ]}')

#2. select col 5 (there is no col 5 - maybe the 5th column, i.e. col 4?)
print(f'2. {x[:, 4]}')

#3. select rows 0 and 1
print(f'3. {x[0:2, ]}')
#or print(x[[0, 1], ])

#4. select columns 2-4
print(f'4. {x[:, 2:5]}')

#5. select row 1 col 4
print(f'5. {x[1,4]}')

#6. select all elements from rows 1 and 2 that are in columns 0, 2 and 4.
print(f'6. {x[1:3, [0, 2, 4]]}')

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]
1. [11 12 13 14 15]
2. [ 5 10 15]
3. [[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
4. [[ 3  4  5]
 [ 8  9 10]
 [13 14 15]]
5. 10
6. [[ 6  8 10]
 [11 13 15]]


In [112]:
# 7.10 (Project: Two-Player, Two-Dimensional Tic-Tac-Toe) 
# Write a script to play two-dimensional Tic-Tac-Toe between two human players who alternate entering their moves on the same computer. 
# Use a 3-by-3 two-dimensional array. Each player indicates their moves by entering a pair of numbers representing the row and column indices 
# of the square in which they want to place their mark, either an 'X' or an 'O'. When the first player moves, place an 'X' in the specified square. 
# When the second player moves, place an 'O'  in the specified square. Each move must be to an empty square. 
# After each move, determine whether the game has been won and whether it’s a draw

import numpy as np
from IPython.display import display, HTML, clear_output #to replace output, rather than printing all output in a column

def play_tictactoe():
    #set up the game board:
    gameboard = np.array([' ']*9).reshape(3, 3)
    # function to convert game board to HTML
    # def gameboard_to_html(gameboard):
    #     html = "<table>"
    #     for row in gameboard:
    #         html += "<tr>"
    #         for cell in row:
    #             html += f"<td>{cell}</td>"
    #         html += "</tr>"
    #     html += "</table>"
    #     return html
    def gameboard_to_html(gameboard):
        html = "<table style='width: 10%; height: 10%;'>"
        for i, row in enumerate(gameboard):
            html += "<tr>"
            for j, cell in enumerate(row):
                if (i + j) % 2 == 0:
                    bgcolor = "#000000"
                else:
                    bgcolor = "#2A2A2A"
                html += f"<td style='background-color: {bgcolor}; width: 33.33%; height: 33.33%; text-align: center; vertical-align: middle; font-size: 1em; padding: 10%;'>{cell}</td>"
            html += "</tr>"
        html += "</table>"
        return html
    # display the game board as HTML
    display(HTML(gameboard_to_html(gameboard)))

    #set up loop until gameover
    gameover = 0
    while not gameover:
        #player 1:
        p1 = None
        while p1 is None: #set up a while loop to repeat asking and checking for user input if it's invalid
            #Player 1 places an X
            try:
                p1 = input('Player 1 place an X (row, column [0-indexed]):\n')
                r, c= map(int, p1.split(','))
                #make sure this in an empty space before placing the X
                if gameboard[r,c] == ' ':
                    gameboard[r,c] = 'X'
                    # clear the output of the current cell
                    clear_output(wait=True)
                    display(HTML(gameboard_to_html(gameboard)))
                else:
                    print("Sorry, you can't go there. Try again.")
                    p1 = None
            except IndexError:
                print(f'{p1} is out of range. Please try again.')
                p1 = None
        #Check if the game has been won:
        Xwin = ['X', 'X', 'X']
        if np.array_equal(gameboard[r,],Xwin) or np.array_equal(gameboard[:,c],Xwin) or np.array_equal(np.diag(gameboard),Xwin) or np.array_equal(np.diag(np.fliplr(gameboard)),Xwin):
            print ('X wins!!')
            gameover = 1
            break
        #Check if the game is a draw:
        if ' ' not in gameboard:
            print("It's a draw...")
            gameover = 1
            break
        #player 2:
        p2 = None
        while p2 is None: #set up a while loop to repeat asking and checking for user input if it's invalid
            #Player 2 places an O
            try:
                p2 = input('Player 2 place an O (row, column [0-indexed]):\n')
                r, c= map(int, p2.split(','))
                #make sure this in an empty space before placing the X
                if gameboard[r,c] == ' ':
                    gameboard[r,c] = 'O'
                    # clear the output of the current cell
                    clear_output(wait=True)
                    display(HTML(gameboard_to_html(gameboard)))
                else:
                    print("Sorry, you can't go there. Try again.")
                    p2 = None
            except IndexError:
                print(f'{p2} is out of range. Please try again.')
                p2 = None
        #Check if the game has been won:
        Owin = ['O', 'O', 'O']
        if np.array_equal(gameboard[r,],Owin) or np.array_equal(gameboard[:,c],Owin) or np.array_equal(np.diag(gameboard),Owin) or np.array_equal(np.diag(np.fliplr(gameboard)),Owin):
            print ('O wins!!')
            gameover = 1
            break
        #Check if the game is a draw:
        if ' ' not in gameboard:
            print("It's a draw...")
            gameover = 1
            break



play_tictactoe()


    
        


X wins!!


In [131]:
#ex7.11 (Challenge Project: Tic-Tac-Toe with Player Against the Computer) 
# Modify your script from the previous exercise so that the computer makes the moves for one of the players. 
# Also, allow the player to specify whether he or she wants to go first or second

import numpy as np
import time
from IPython.display import display, HTML, clear_output #to replace output, rather than printing all output in a column

def playerchoice(XO):
    p = input(f'Player 1 place an {XO} (row, column [0-indexed]):\n')
    r, c= map(int, p.split(','))
    return r, c

def computerchoice(gameboard):
    print("Computer's turn")
    # pause the execution of the code for 2 seconds
    time.sleep(2)
    # find the indices of the gameboard elements that equal ' '
    indices = np.where(gameboard == ' ')
    # select a random index from the indices
    random_index = np.random.choice(len(indices[0]))
    # get the row and column indices of the random element
    r, c = indices[0][random_index], indices[1][random_index]
    return r, c
    
    

def play_tictactoe():
    playerfirst = None
    while playerfirst == None:
        playerfirst = int(input("Who plays first? Computer(0) or you(1)?\n"))
        if playerfirst not in (0, 1):
            print('Please enter either 0 (computer plays first) or 1 (you play first)\n')
            playerfirst = None
    #set up the game board:
    gameboard = np.array([' ']*9).reshape(3, 3)
    # function to convert game board to HTML (looks nicer and each new iteration of the game board replaces the old one)
    def gameboard_to_html(gameboard):
        html = "<table style='width: 10%; height: 10%;'>"
        for i, row in enumerate(gameboard):
            html += "<tr>"
            for j, cell in enumerate(row):
                if (i + j) % 2 == 0:
                    bgcolor = "#000000"
                else:
                    bgcolor = "#2A2A2A"
                html += f"<td style='background-color: {bgcolor}; width: 33.33%; height: 33.33%; text-align: center; vertical-align: middle; font-size: 1em; padding: 10%;'>{cell}</td>"
            html += "</tr>"
        html += "</table>"
        return html
    # display the game board as HTML
    display(HTML(gameboard_to_html(gameboard)))

    #set up loop until gameover
    gameover = 0
    while not gameover:
        if playerfirst == 1:
            XO = 'X'
            #player 1:
            r = None
            while r is None: #set up a while loop to repeat asking and checking for user input if it's invalid
                #Player 1 places an X
                try:
                    r, c = playerchoice(XO)
                    #make sure this in an empty space before placing the X
                    if gameboard[r,c] == ' ':
                        gameboard[r,c] = 'X'
                        # clear the output of the current cell
                        clear_output(wait=True)
                        display(HTML(gameboard_to_html(gameboard)))
                    else:
                        print("Sorry, you can't go there. Try again.")
                        r = None
                except IndexError:
                    print(f'{r, c} is out of range. Please try again.')
                    r = None
            #Check if the game has been won:
            Xwin = ['X', 'X', 'X']
            if np.array_equal(gameboard[r,],Xwin) or np.array_equal(gameboard[:,c],Xwin) or np.array_equal(np.diag(gameboard),Xwin) or np.array_equal(np.diag(np.fliplr(gameboard)),Xwin):
                print ('X wins!!')
                gameover = 1
                break
            #Check if the game is a draw:
            if ' ' not in gameboard:
                print("It's a draw...")
                gameover = 1
                break
            #player 2:
            #Player 2 places an O
            r, c = computerchoice(gameboard)
            #make sure this in an empty space before placing the X
            gameboard[r,c] = 'O'
            # clear the output of the current cell
            clear_output(wait=True)
            display(HTML(gameboard_to_html(gameboard)))
            #Check if the game has been won:
            Owin = ['O', 'O', 'O']
            if np.array_equal(gameboard[r,],Owin) or np.array_equal(gameboard[:,c],Owin) or np.array_equal(np.diag(gameboard),Owin) or np.array_equal(np.diag(np.fliplr(gameboard)),Owin):
                print ('O wins!!')
                gameover = 1
                break
            #Check if the game is a draw:
            if ' ' not in gameboard:
                print("It's a draw...")
                gameover = 1
                break
        if playerfirst == 0:
            XO = 'O'
            #player 1:
            r, c = computerchoice(gameboard)
            gameboard[r,c] = 'X'
            # clear the output of the current cell
            clear_output(wait=True)
            display(HTML(gameboard_to_html(gameboard)))
            #Check if the game has been won:
            Xwin = ['X', 'X', 'X']
            if np.array_equal(gameboard[r,],Xwin) or np.array_equal(gameboard[:,c],Xwin) or np.array_equal(np.diag(gameboard),Xwin) or np.array_equal(np.diag(np.fliplr(gameboard)),Xwin):
                print ('X wins!!')
                gameover = 1
                break
            #Check if the game is a draw:
            if ' ' not in gameboard:
                print("It's a draw...")
                gameover = 1
                break
            #player 2:
            r = None
            while r is None: #set up a while loop to repeat asking and checking for user input if it's invalid
                #Player 2 places an O
                try:
                    r, c = playerchoice(XO)
                    #make sure this in an empty space before placing the X
                    if gameboard[r,c] == ' ':
                        gameboard[r,c] = 'O'
                        # clear the output of the current cell
                        clear_output(wait=True)
                        display(HTML(gameboard_to_html(gameboard)))
                    else:
                        print("Sorry, you can't go there. Try again.")
                        r = None
                except IndexError:
                    print(f'{r, c} is out of range. Please try again.')
                    r = None
            #Check if the game has been won:
            Owin = ['O', 'O', 'O']
            if np.array_equal(gameboard[r,],Owin) or np.array_equal(gameboard[:,c],Owin) or np.array_equal(np.diag(gameboard),Owin) or np.array_equal(np.diag(np.fliplr(gameboard)),Owin):
                print ('O wins!!')
                gameover = 1
                break
            #Check if the game is a draw:
            if ' ' not in gameboard:
                print("It's a draw...")
                gameover = 1
                break



play_tictactoe()


X wins!!


In [147]:
#ex7.12 (Super Challenge Project: 3D Tic-Tac-Toe with Player Against the Computer) 
# Develop a script that plays three-dimensional Tic-Tac-Toe on a 4-by-4-by-4 board. [Note: This is an extremely challenging project! ]

import numpy as np
import time
from IPython.display import display, HTML, clear_output #to replace output, rather than printing all output in a column

def playerchoice(XO):
    p = input(f'Player 1 place an {XO} (level, row, column [0-indexed]):\n')
    z, r, c= map(int, p.split(','))
    return z, r, c

def computerchoice(gameboard):
    print("Computer's turn")
    # pause the execution of the code for 2 seconds
    time.sleep(2)
    # find the indices of the gameboard elements that equal ' '
    indices = np.where(gameboard == ' ')
    # select a random index from the indices
    random_index = np.random.choice(len(indices[0]))
    # get the row and column indices of the random element
    z ,r, c = indices[0][random_index], indices[1][random_index], indices[2][random_index]
    return z, r, c
    
    

def play_3dtictactoe():
    playerfirst = None
    while playerfirst == None:
        playerfirst = int(input("Who plays first? Computer(0) or you(1)?\n"))
        if playerfirst not in (0, 1):
            print('Please enter either 0 (computer plays first) or 1 (you play first)\n')
            playerfirst = None
    #set up the game board:
    gameboard = np.array([' ']*64).reshape(4,4,4)
    # function to convert game board to HTML (looks nicer and each new iteration of the game board replaces the old one)
    def gameboard_to_html(gameboard):
        html = "<table style='width: 100%; height: 100%;'>"
        html += "<tr>"
        for z, level in enumerate(gameboard):
            html += "<td style='width: 10%;'>"
            html += "<table style='width: 25%; height: 100%;'>"
            for i, row in enumerate(level):
                html += "<tr>"
                for j, cell in enumerate(row):
                    if (z + i + j) % 2 == 0:
                        bgcolor = "#000000"
                    else:
                        bgcolor = "#2A2A2A"
                    html += f"<td style='background-color: {bgcolor}; width: 25%; height: 25%; text-align: center; vertical-align: middle; font-size: 1em; padding: 10%;'>{cell}</td>"
                html += "</tr>"
            html += "</table>"
            html += "</td>"
        html += "</tr>"
        html += "</table>"
        return html
    # display the game board as HTML
    display(HTML(gameboard_to_html(gameboard)))

    #set up loop until gameover
    gameover = 0
    while not gameover:
        if playerfirst == 1:
            XO = 'X'
            #player 1:
            r = None
            while r is None: #set up a while loop to repeat asking and checking for user input if it's invalid
                #Player 1 places an X
                try:
                    z, r, c = playerchoice(XO)
                    #make sure this in an empty space before placing the X
                    if gameboard[z, r,c] == ' ':
                        gameboard[z, r,c] = 'X'
                        # clear the output of the current gameboard
                        clear_output(wait=True)
                        display(HTML(gameboard_to_html(gameboard)))
                    else:
                        print("Sorry, you can't go there. Try again.")
                        r = None
                except IndexError:
                    print(f'{z, r, c} is out of range. Please try again.')
                    r = None
            #Check if the game has been won:
            Xwin = ['X', 'X', 'X', 'X']
            if (np.array_equal(gameboard[z, r,:],Xwin) or np.array_equal(gameboard[z,:,c],Xwin) or np.array_equal(gameboard[:,r,c],Xwin) or  #column, row, or z-slice
                np.array_equal(np.diag(gameboard[z]),Xwin) or np.array_equal(np.diag(np.fliplr(gameboard[z])),Xwin) or #diagonals within each z-plane
                np.array_equal(np.diag(gameboard[:,r,:]), Xwin) or np.array_equal(np.diag(np.fliplr(gameboard[:,r,:])), Xwin) or #diagonals within each row
                np.array_equal(np.diag(gameboard[:,:,c]), Xwin) or np.array_equal(np.diag(np.fliplr(gameboard[:,:,c])), Xwin) or #diagonals within each column
                #finally, true 3-d diagonals cutting through levels, rows, and cols
                np.array_equal(gameboard[(0,1,2,3), (0,1,2,3), (0,1,2,3)], Xwin) or np.array_equal(gameboard[(0,1,2,3),(0,1,2,3),(3,2,1,0)], Xwin) or 
                np.array_equal(gameboard[(0,1,2,3),(3,2,1,0),(0,1,2,3)], Xwin) or np.array_equal(gameboard[(0,1,2,3),(3,2,1,0),(3,2,1,0)], Xwin)):
                print ('X wins!!')
                gameover = 1
                break
            #Check if the game is a draw:
            if ' ' not in gameboard:
                print("It's a draw...")
                gameover = 1
                break
            #player 2:
            #Player 2 places an O
            z, r, c = computerchoice(gameboard)
            #make sure this in an empty space before placing the X
            gameboard[z,r,c] = 'O'
            # clear the output of the current cell
            clear_output(wait=True)
            display(HTML(gameboard_to_html(gameboard)))
            #Check if the game has been won:
            Owin = ['O', 'O', 'O', 'O']
            if (np.array_equal(gameboard[z, r,:],Owin) or np.array_equal(gameboard[z,:,c],Owin) or np.array_equal(gameboard[:,r,c],Owin) or  #column, row, or z-slice
                np.array_equal(np.diag(gameboard[z]),Owin) or np.array_equal(np.diag(np.fliplr(gameboard[z])),Owin) or #diagonals within each z-plane
                np.array_equal(np.diag(gameboard[:,r,:]), Owin) or np.array_equal(np.diag(np.fliplr(gameboard[:,r,:])), Owin) or #diagonals within each row
                np.array_equal(np.diag(gameboard[:,:,c]), Owin) or np.array_equal(np.diag(np.fliplr(gameboard[:,:,c])), Owin) or #diagonals within each column
                #finally, true 3-d diagonals cutting through levels, rows, and cols
                np.array_equal(gameboard[(0,1,2,3), (0,1,2,3), (0,1,2,3)], Owin) or np.array_equal(gameboard[(0,1,2,3),(0,1,2,3),(3,2,1,0)], Owin) or 
                np.array_equal(gameboard[(0,1,2,3),(3,2,1,0),(0,1,2,3)], Owin) or np.array_equal(gameboard[(0,1,2,3),(3,2,1,0),(3,2,1,0)], Owin)):
                print ('O wins!!')
                gameover = 1
                break
            #Check if the game is a draw:
            if ' ' not in gameboard:
                print("It's a draw...")
                gameover = 1
                break
        if playerfirst == 0:
            XO = 'O'
            #player 1:
            z, r, c = computerchoice(gameboard)
            gameboard[z,r,c] = 'X'
            # clear the output of the current cell
            clear_output(wait=True)
            display(HTML(gameboard_to_html(gameboard)))
            #Check if the game has been won:
            Xwin = ['X', 'X', 'X', 'X']
            if (np.array_equal(gameboard[z, r,:],Xwin) or np.array_equal(gameboard[z,:,c],Xwin) or np.array_equal(gameboard[:,r,c],Xwin) or  #column, row, or z-slice
                np.array_equal(np.diag(gameboard[z]),Xwin) or np.array_equal(np.diag(np.fliplr(gameboard[z])),Xwin) or #diagonals within each z-plane
                np.array_equal(np.diag(gameboard[:,r,:]), Xwin) or np.array_equal(np.diag(np.fliplr(gameboard[:,r,:])), Xwin) or #diagonals within each row
                np.array_equal(np.diag(gameboard[:,:,c]), Xwin) or np.array_equal(np.diag(np.fliplr(gameboard[:,:,c])), Xwin) or #diagonals within each column
                #finally, true 3-d diagonals cutting through levels, rows, and cols
                np.array_equal(gameboard[(0,1,2,3), (0,1,2,3), (0,1,2,3)], Xwin) or np.array_equal(gameboard[(0,1,2,3),(0,1,2,3),(3,2,1,0)], Xwin) or 
                np.array_equal(gameboard[(0,1,2,3),(3,2,1,0),(0,1,2,3)], Xwin) or np.array_equal(gameboard[(0,1,2,3),(3,2,1,0),(3,2,1,0)], Xwin)):
                print ('X wins!!')
                gameover = 1
                break
            #Check if the game is a draw:
            if ' ' not in gameboard:
                print("It's a draw...")
                gameover = 1
                break
            #player 2:
            r = None
            while r is None: #set up a while loop to repeat asking and checking for user input if it's invalid
                #Player 2 places an O
                try:
                    z, r, c = playerchoice(XO)
                    #make sure this in an empty space before placing the X
                    if gameboard[z,r,c] == ' ':
                        gameboard[z,r,c] = 'O'
                        # clear the output of the current cell
                        clear_output(wait=True)
                        display(HTML(gameboard_to_html(gameboard)))
                    else:
                        print("Sorry, you can't go there. Try again.")
                        r = None
                except IndexError:
                    print(f'{r, c} is out of range. Please try again.')
                    r = None
            #Check if the game has been won:
            Owin = ['O', 'O', 'O', 'O']
            if (np.array_equal(gameboard[z, r,:],Owin) or np.array_equal(gameboard[z,:,c],Owin) or np.array_equal(gameboard[:,r,c],Owin) or  #column, row, or z-slice
                np.array_equal(np.diag(gameboard[z]),Owin) or np.array_equal(np.diag(np.fliplr(gameboard[z])),Owin) or #diagonals within each z-plane
                np.array_equal(np.diag(gameboard[:,r,:]), Owin) or np.array_equal(np.diag(np.fliplr(gameboard[:,r,:])), Owin) or #diagonals within each row
                np.array_equal(np.diag(gameboard[:,:,c]), Owin) or np.array_equal(np.diag(np.fliplr(gameboard[:,:,c])), Owin) or #diagonals within each column
                #finally, true 3-d diagonals cutting through levels, rows, and cols
                np.array_equal(gameboard[(0,1,2,3), (0,1,2,3), (0,1,2,3)], Owin) or np.array_equal(gameboard[(0,1,2,3),(0,1,2,3),(3,2,1,0)], Owin) or 
                np.array_equal(gameboard[(0,1,2,3),(3,2,1,0),(0,1,2,3)], Owin) or np.array_equal(gameboard[(0,1,2,3),(3,2,1,0),(3,2,1,0)], Owin)):
                print ('O wins!!')
                gameover = 1
                break
            #Check if the game is a draw:
            if ' ' not in gameboard:
                print("It's a draw...")
                gameover = 1
                break



play_3dtictactoe()


X wins!!


In [152]:
#ex7.14 (Horizontal and Vertical Stacking) 
import numpy as np

#Create the two-dimensional arrays:
array1 = np.array([[0,1], [2,3]])
array2 = np.array([[4,5],[6,7]])

#1.Use vertical stacking to create the 4-by-2 array named array3 with array1 stacked on top of array2.
array3 = np.vstack((array1, array2))
print('array3')
print(array3)

#2. Use horizontal stacking to create the 2-by-4 array named array4 with array2 to the right of array1
array4 = np.hstack((array1, array2))
print('array4')
print(array4)

#3. Use vertical stacking with two copies of array4 to create a 4-by-4 array5
array5 = np.vstack((array4, array4))
print('array5')
print(array5)

#4. Use horizontal stacking with two copies of array3 to create a 4-by-4 array6
array6 = np.hstack((array3, array3))
print('array6')
print(array6)

array3
[[0 1]
 [2 3]
 [4 5]
 [6 7]]
array4
[[0 1 4 5]
 [2 3 6 7]]
array5
[[0 1 4 5]
 [2 3 6 7]
 [0 1 4 5]
 [2 3 6 7]]
array6
[[0 1 0 1]
 [2 3 2 3]
 [4 5 4 5]
 [6 7 6 7]]


In [156]:
#ex.7.15 Research NumPy function concatenate, then use it to reimplement the previous exercise

import numpy as np

#Create the two-dimensional arrays:
array1 = np.array([[0,1], [2,3]])
array2 = np.array([[4,5],[6,7]])

#1.create the 4-by-2 array named array3 with array1 stacked on top of array2.
array3 = np.concatenate((array1, array2), axis = 0) #axis = 0 produces vertical stack
print('array3')
print(array3)

#2. create the 2-by-4 array named array4 with array2 to the right of array1
array4 = np.concatenate((array1, array2), axis = 1) #axis = 1 produces horizontal stack
print('array4')
print(array4)

#3. Use two copies of array4 to create a 4-by-4 array5 with one on top of the other
array5 = np.concatenate((array4, array4), axis = 0)
print('array5')
print(array5)

#4. Use  two copies of array3 to create a 4-by-4 array6 side-by-side
array6 = np.concatenate((array3, array3), axis = 1)
print('array6')
print(array6)

array3
[[0 1]
 [2 3]
 [4 5]
 [6 7]]
array4
[[0 1 4 5]
 [2 3 6 7]]
array5
[[0 1 4 5]
 [2 3 6 7]
 [0 1 4 5]
 [2 3 6 7]]
array6
[[0 1 0 1]
 [2 3 2 3]
 [4 5 4 5]
 [6 7 6 7]]


In [173]:
#ex7.16 Research and use NumPy’s tile function to create a checkerboard pattern of dashes and asterisks

a = np.array([['*','-'], ['-','*']])
a1 = np.tile(a, (8,8))

for row in range(a1.shape[0]):
    for element in range(a1.shape[1]):
        print(a1[row, element], end = '  ')
    print()

*  -  *  -  *  -  *  -  *  -  *  -  *  -  *  -  
-  *  -  *  -  *  -  *  -  *  -  *  -  *  -  *  
*  -  *  -  *  -  *  -  *  -  *  -  *  -  *  -  
-  *  -  *  -  *  -  *  -  *  -  *  -  *  -  *  
*  -  *  -  *  -  *  -  *  -  *  -  *  -  *  -  
-  *  -  *  -  *  -  *  -  *  -  *  -  *  -  *  
*  -  *  -  *  -  *  -  *  -  *  -  *  -  *  -  
-  *  -  *  -  *  -  *  -  *  -  *  -  *  -  *  
*  -  *  -  *  -  *  -  *  -  *  -  *  -  *  -  
-  *  -  *  -  *  -  *  -  *  -  *  -  *  -  *  
*  -  *  -  *  -  *  -  *  -  *  -  *  -  *  -  
-  *  -  *  -  *  -  *  -  *  -  *  -  *  -  *  
*  -  *  -  *  -  *  -  *  -  *  -  *  -  *  -  
-  *  -  *  -  *  -  *  -  *  -  *  -  *  -  *  
*  -  *  -  *  -  *  -  *  -  *  -  *  -  *  -  
-  *  -  *  -  *  -  *  -  *  -  *  -  *  -  *  


In [178]:
#ex7.17 Research and use the NumPy bincount function to count the number of occurrences 
# of each non-negative integer in a 5-by-5 array of random integers in the range 0–99
import numpy as np

a = np.array([np.random.randint(0, 100, size = 25)]).reshape(5, 5)
print(a)

np.bincount(a.flatten())

[[58 20 34 28 30]
 [40 18  9 59 86]
 [31 41 51 73 49]
 [90 58 11 20 48]
 [68 24 45 35 90]]


array([0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 2, 0,
       0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0,
       0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 2, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 2], dtype=int64)

In [193]:
#ex7.18 (Median and Mode of an array) 
# NumPy arrays offer a mean method, but not median or mode. Write functions median and mode that use existing NumPy capabilities 
# to determine the median (middle) and mode (most frequent) of the values in an array. Your functions should determine the median 
# and mode regardless of the array’s shape. Test your function on three arrays of different shapes.

def np_median(a):
    x = sorted(a.flatten())
    mid = len(x)//2
    #if x has an odd number of elements:
    if len(x)%2 !=0:
        median = x[mid]
    #if x has an even number of elements:
    else:
        median = (x[mid] + x[mid-1])/2
    return median

print(np_median(np.array([0, 1, 2, 3])))

print(np_median(np.array([0, 1, 2])))

print(np_median(np.arange(6).reshape(2, 3)))


def np_mode(a):
    x = np.bincount(a.flatten())
    xx = np.where(x==max(x))[0]
    if len(xx) == 1:
        mode = xx[0]
    else:
        mode = [xx[i] for i in range(len(xx))]
    return mode

print(np_mode(np.array([[1, 2, 1],[0,1,2],[2,3,4]])))


1.5
1
2.5
[1, 2]


In [209]:
#ex7.19 (Enhanced Median and Mode of an array) 
# Modify your functions from the previous exercise to allow the user to provide an axis keyword argument so the 
# calculations can be performed row-by-row or column-by-column on a two-dimensional array

def np_median(a, axis=0):
    medians = []
    for i in range(a.shape[axis]):
        if axis == 1:
            x = sorted(a[:,i])
        else:
            x = sorted(a[i])
        mid = len(x)//2
        #if x has an odd number of elements:
        if len(x)%2 !=0:
            median = x[mid]
        #if x has an even number of elements:
        else:
            median = (x[mid] + x[mid-1])/2
        medians.append(median)
    return(medians)


x = np.array(np.random.randint(1, 5, size = 16)).reshape(4, 4)
print(x)
print(np_median(x, axis = 0))
print(np_median(x, axis = 1))


def np_mode(a, axis = 0):
    modes = []
    for i in range(a.shape[axis]):
        if axis == 1:
            x = np.bincount(a[:,i])
        else:
            x = np.bincount(a[i])
        xx = np.where(x == max(x))[0]
        if len(xx) == 1:
            mode = xx[0]
        else:
            mode = [xx[i] for i in range(len(xx))]
        modes.append(mode)
    return(modes)

print(np_mode(x, axis = 0))
print(np_mode(x, axis = 1))

[[2 3 2 3]
 [3 3 2 3]
 [4 4 3 1]
 [4 4 2 4]]
[2.5, 3.0, 3.5, 4.0]
[3.5, 3.5, 2.0, 3.0]
[[2, 3], 3, 4, 4]
[4, [3, 4], 2, 3]


In [ ]:
#ex7.20 (Performance Analysis) 
# In this chapter, we used %timeit to compare the average execution times of generating a list of 6,000,000 random die rolls vs. generating an array of 6,000,000 random die rolls. 
# Though we saw approximately two orders of magnitude performance improvement with array, we generated the list and the array using two different random-number generators 
# and different techniques for building each collection. If you use the same techniques we showed to generate a one-element list and a one-element array, creating the list is slightly faster. 
# Repeat the %timeit operations for one-element collections. Then do it again for 10, 100, 1000, 10,000, 100,000, and 1,000,000 elements and compare the results on your system. 

%timeit