In [3]:
#ex7.3 Element-wise array multiplication
#Create a 3x3 array containing the even integers from 2 through 18. Create a second 3x3 array containing the integers from 9 to 1. Multiply them.

import numpy as np

a1 = np.array([x for x in range(1, 19) if x%2 == 0])
a2 = np.arange(9, 0, -1)

a1 * a2

array([18, 32, 42, 48, 50, 48, 42, 32, 18])

In [6]:
#ex7.5 Flattening arrays (flatten v ravel methods)
#Create a 2x3 array containing the first 6 powers of 2. Flaten the array with flatten and then ravel. Display the result and the original array.

import numpy as np

a1 = np.array([2**x for x in range(6)]).reshape(2,3)

f1 = a1.flatten()
r1 = a1.ravel()

print('flatten')
print(a1)
print(f1)

print('\nravel')
print(a1)
print(r1)

flatten
[[ 1  2  4]
 [ 8 16 32]]
[ 1  2  4  8 16 32]

ravel
[[ 1  2  4]
 [ 8 16 32]]
[ 1  2  4  8 16 32]


In [4]:
#ex7.6 Research array method astype
#Use linspace and reshape to create a 2*3 array with values 1.1, 2.2, ... 6.6, then use astype to convert the array to an array of integers
import numpy as np

a1 = np.linspace(1.1, 6.6, 6).reshape(2, 3)
print(a1)

a1 = a1.astype(int)
print(a1)

[[1.1 2.2 3.3]
 [4.4 5.5 6.6]]
[[1 2 3]
 [4 5 6]]


In [25]:
#ex7.7 Challenge project: reimplement NumPy array Output
#write a function that reimplements NumPy’s array formatting for two-dimensional arrays using loops. Assume the array contains only positive integer values.
#(NumPy outputs two-dimensional arrays in a nice column-based format that right-aligns every element in a field width.
#The field width’s size is determined by the array element value that requires the most character positions to display.)

def nparray(int_from, int_to, nrow, ncol):
    x = [i for i in range(int_from, int_to)]
    maxwidth = len(str(max(x)))
    for r in range(nrow):
        for c in range(ncol):
            print(f'{x[r*ncol + c]:>{maxwidth}}', end = ' ')
        print('')
                


nparray(0, 12, 3, 4)

 0  1  2  3 
 4  5  6  7 
 8  9 10 11 


In [43]:
#ex7.7 Challenge project: reimplement DataFrame Output
#write a function that reimplements pandas DataFrame formatting using loops. Assume the DataFrame contains only positive integer values and row and column names are ints beginning wtih 0.
#(pandas displays DataFrames in a nice column-based format with row and column labels that right-aligns every element in a column based on the columns widest value.)

def pddf(vals, nrows, ncols):
    #get max width of values in vals for formatting:
    maxwidth = len(str(max(vals)))
    #print column labels
    print(' '*maxwidth, end = ' ')
    for col in range(ncols):
        print(f'{col:>{maxwidth}}', end = ' ')
    print() #print a new line after the col labels
    #print row values preceded by row label
    for row in range(nrows):
        print(f'{row:>{maxwidth}}', end = ' ')
        for col in range(ncols):
            print(f'{vals[row*ncols + col]:>{maxwidth}}', end = ' ')
        print()


pddf([i for i in range(99, 111)], 3, 4)

      0   1   2   3 
  0  99 100 101 102 
  1 103 104 105 106 
  2 107 108 109 110 


In [65]:
#ex7.9 (Indexing and Slicing arrays) 
#Create an array containing the values 1–15, reshape it into a 3-by-5 array, then use indexing and slicing techniques to perform each of the following operations

import numpy as np

x = np.arange(1, 16).reshape(3, 5)
print(x)

#1. seelct row 2
print(f'1. {x[2, ]}')

#2. select col 5 (there is no col 5 - maybe the 5th column, i.e. col 4?)
print(f'2. {x[:, 4]}')

#3. select rows 0 and 1
print(f'3. {x[0:2, ]}')
#or print(x[[0, 1], ])

#4. select columns 2-4
print(f'4. {x[:, 2:5]}')

#5. select row 1 col 4
print(f'5. {x[1,4]}')

#6. select all elements from rows 1 and 2 that are in columns 0, 2 and 4.
print(f'6. {x[1:3, [0, 2, 4]]}')

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]
1. [11 12 13 14 15]
2. [ 5 10 15]
3. [[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
4. [[ 3  4  5]
 [ 8  9 10]
 [13 14 15]]
5. 10
6. [[ 6  8 10]
 [11 13 15]]


In [112]:
# 7.10 (Project: Two-Player, Two-Dimensional Tic-Tac-Toe) 
# Write a script to play two-dimensional Tic-Tac-Toe between two human players who alternate entering their moves on the same computer. 
# Use a 3-by-3 two-dimensional array. Each player indicates their moves by entering a pair of numbers representing the row and column indices 
# of the square in which they want to place their mark, either an 'X' or an 'O'. When the first player moves, place an 'X' in the specified square. 
# When the second player moves, place an 'O'  in the specified square. Each move must be to an empty square. 
# After each move, determine whether the game has been won and whether it’s a draw

import numpy as np
from IPython.display import display, HTML, clear_output #to replace output, rather than printing all output in a column

def play_tictactoe():
    #set up the game board:
    gameboard = np.array([' ']*9).reshape(3, 3)
    # function to convert game board to HTML
    # def gameboard_to_html(gameboard):
    #     html = "<table>"
    #     for row in gameboard:
    #         html += "<tr>"
    #         for cell in row:
    #             html += f"<td>{cell}</td>"
    #         html += "</tr>"
    #     html += "</table>"
    #     return html
    def gameboard_to_html(gameboard):
        html = "<table style='width: 10%; height: 10%;'>"
        for i, row in enumerate(gameboard):
            html += "<tr>"
            for j, cell in enumerate(row):
                if (i + j) % 2 == 0:
                    bgcolor = "#000000"
                else:
                    bgcolor = "#2A2A2A"
                html += f"<td style='background-color: {bgcolor}; width: 33.33%; height: 33.33%; text-align: center; vertical-align: middle; font-size: 1em; padding: 10%;'>{cell}</td>"
            html += "</tr>"
        html += "</table>"
        return html
    # display the game board as HTML
    display(HTML(gameboard_to_html(gameboard)))

    #set up loop until gameover
    gameover = 0
    while not gameover:
        #player 1:
        p1 = None
        while p1 is None: #set up a while loop to repeat asking and checking for user input if it's invalid
            #Player 1 places an X
            try:
                p1 = input('Player 1 place an X (row, column [0-indexed]):\n')
                r, c= map(int, p1.split(','))
                #make sure this in an empty space before placing the X
                if gameboard[r,c] == ' ':
                    gameboard[r,c] = 'X'
                    # clear the output of the current cell
                    clear_output(wait=True)
                    display(HTML(gameboard_to_html(gameboard)))
                else:
                    print("Sorry, you can't go there. Try again.")
                    p1 = None
            except IndexError:
                print(f'{p1} is out of range. Please try again.')
                p1 = None
        #Check if the game has been won:
        Xwin = ['X', 'X', 'X']
        if np.array_equal(gameboard[r,],Xwin) or np.array_equal(gameboard[:,c],Xwin) or np.array_equal(np.diag(gameboard),Xwin) or np.array_equal(np.diag(np.fliplr(gameboard)),Xwin):
            print ('X wins!!')
            gameover = 1
            break
        #Check if the game is a draw:
        if ' ' not in gameboard:
            print("It's a draw...")
            gameover = 1
            break
        #player 2:
        p2 = None
        while p2 is None: #set up a while loop to repeat asking and checking for user input if it's invalid
            #Player 2 places an O
            try:
                p2 = input('Player 2 place an O (row, column [0-indexed]):\n')
                r, c= map(int, p2.split(','))
                #make sure this in an empty space before placing the X
                if gameboard[r,c] == ' ':
                    gameboard[r,c] = 'O'
                    # clear the output of the current cell
                    clear_output(wait=True)
                    display(HTML(gameboard_to_html(gameboard)))
                else:
                    print("Sorry, you can't go there. Try again.")
                    p2 = None
            except IndexError:
                print(f'{p2} is out of range. Please try again.')
                p2 = None
        #Check if the game has been won:
        Owin = ['O', 'O', 'O']
        if np.array_equal(gameboard[r,],Owin) or np.array_equal(gameboard[:,c],Owin) or np.array_equal(np.diag(gameboard),Owin) or np.array_equal(np.diag(np.fliplr(gameboard)),Owin):
            print ('O wins!!')
            gameover = 1
            break
        #Check if the game is a draw:
        if ' ' not in gameboard:
            print("It's a draw...")
            gameover = 1
            break



play_tictactoe()


    
        


X wins!!


In [131]:
#ex7.11 (Challenge Project: Tic-Tac-Toe with Player Against the Computer) 
# Modify your script from the previous exercise so that the computer makes the moves for one of the players. 
# Also, allow the player to specify whether he or she wants to go first or second

import numpy as np
import time
from IPython.display import display, HTML, clear_output #to replace output, rather than printing all output in a column

def playerchoice(XO):
    p = input(f'Player 1 place an {XO} (row, column [0-indexed]):\n')
    r, c= map(int, p.split(','))
    return r, c

def computerchoice(gameboard):
    print("Computer's turn")
    # pause the execution of the code for 2 seconds
    time.sleep(2)
    # find the indices of the gameboard elements that equal ' '
    indices = np.where(gameboard == ' ')
    # select a random index from the indices
    random_index = np.random.choice(len(indices[0]))
    # get the row and column indices of the random element
    r, c = indices[0][random_index], indices[1][random_index]
    return r, c
    
    

def play_tictactoe():
    playerfirst = None
    while playerfirst == None:
        playerfirst = int(input("Who plays first? Computer(0) or you(1)?\n"))
        if playerfirst not in (0, 1):
            print('Please enter either 0 (computer plays first) or 1 (you play first)\n')
            playerfirst = None
    #set up the game board:
    gameboard = np.array([' ']*9).reshape(3, 3)
    # function to convert game board to HTML (looks nicer and each new iteration of the game board replaces the old one)
    def gameboard_to_html(gameboard):
        html = "<table style='width: 10%; height: 10%;'>"
        for i, row in enumerate(gameboard):
            html += "<tr>"
            for j, cell in enumerate(row):
                if (i + j) % 2 == 0:
                    bgcolor = "#000000"
                else:
                    bgcolor = "#2A2A2A"
                html += f"<td style='background-color: {bgcolor}; width: 33.33%; height: 33.33%; text-align: center; vertical-align: middle; font-size: 1em; padding: 10%;'>{cell}</td>"
            html += "</tr>"
        html += "</table>"
        return html
    # display the game board as HTML
    display(HTML(gameboard_to_html(gameboard)))

    #set up loop until gameover
    gameover = 0
    while not gameover:
        if playerfirst == 1:
            XO = 'X'
            #player 1:
            r = None
            while r is None: #set up a while loop to repeat asking and checking for user input if it's invalid
                #Player 1 places an X
                try:
                    r, c = playerchoice(XO)
                    #make sure this in an empty space before placing the X
                    if gameboard[r,c] == ' ':
                        gameboard[r,c] = 'X'
                        # clear the output of the current cell
                        clear_output(wait=True)
                        display(HTML(gameboard_to_html(gameboard)))
                    else:
                        print("Sorry, you can't go there. Try again.")
                        r = None
                except IndexError:
                    print(f'{r, c} is out of range. Please try again.')
                    r = None
            #Check if the game has been won:
            Xwin = ['X', 'X', 'X']
            if np.array_equal(gameboard[r,],Xwin) or np.array_equal(gameboard[:,c],Xwin) or np.array_equal(np.diag(gameboard),Xwin) or np.array_equal(np.diag(np.fliplr(gameboard)),Xwin):
                print ('X wins!!')
                gameover = 1
                break
            #Check if the game is a draw:
            if ' ' not in gameboard:
                print("It's a draw...")
                gameover = 1
                break
            #player 2:
            #Player 2 places an O
            r, c = computerchoice(gameboard)
            #make sure this in an empty space before placing the X
            gameboard[r,c] = 'O'
            # clear the output of the current cell
            clear_output(wait=True)
            display(HTML(gameboard_to_html(gameboard)))
            #Check if the game has been won:
            Owin = ['O', 'O', 'O']
            if np.array_equal(gameboard[r,],Owin) or np.array_equal(gameboard[:,c],Owin) or np.array_equal(np.diag(gameboard),Owin) or np.array_equal(np.diag(np.fliplr(gameboard)),Owin):
                print ('O wins!!')
                gameover = 1
                break
            #Check if the game is a draw:
            if ' ' not in gameboard:
                print("It's a draw...")
                gameover = 1
                break
        if playerfirst == 0:
            XO = 'O'
            #player 1:
            r, c = computerchoice(gameboard)
            gameboard[r,c] = 'X'
            # clear the output of the current cell
            clear_output(wait=True)
            display(HTML(gameboard_to_html(gameboard)))
            #Check if the game has been won:
            Xwin = ['X', 'X', 'X']
            if np.array_equal(gameboard[r,],Xwin) or np.array_equal(gameboard[:,c],Xwin) or np.array_equal(np.diag(gameboard),Xwin) or np.array_equal(np.diag(np.fliplr(gameboard)),Xwin):
                print ('X wins!!')
                gameover = 1
                break
            #Check if the game is a draw:
            if ' ' not in gameboard:
                print("It's a draw...")
                gameover = 1
                break
            #player 2:
            r = None
            while r is None: #set up a while loop to repeat asking and checking for user input if it's invalid
                #Player 2 places an O
                try:
                    r, c = playerchoice(XO)
                    #make sure this in an empty space before placing the X
                    if gameboard[r,c] == ' ':
                        gameboard[r,c] = 'O'
                        # clear the output of the current cell
                        clear_output(wait=True)
                        display(HTML(gameboard_to_html(gameboard)))
                    else:
                        print("Sorry, you can't go there. Try again.")
                        r = None
                except IndexError:
                    print(f'{r, c} is out of range. Please try again.')
                    r = None
            #Check if the game has been won:
            Owin = ['O', 'O', 'O']
            if np.array_equal(gameboard[r,],Owin) or np.array_equal(gameboard[:,c],Owin) or np.array_equal(np.diag(gameboard),Owin) or np.array_equal(np.diag(np.fliplr(gameboard)),Owin):
                print ('O wins!!')
                gameover = 1
                break
            #Check if the game is a draw:
            if ' ' not in gameboard:
                print("It's a draw...")
                gameover = 1
                break



play_tictactoe()


X wins!!


In [147]:
#ex7.12 (Super Challenge Project: 3D Tic-Tac-Toe with Player Against the Computer) 
# Develop a script that plays three-dimensional Tic-Tac-Toe on a 4-by-4-by-4 board. [Note: This is an extremely challenging project! ]

import numpy as np
import time
from IPython.display import display, HTML, clear_output #to replace output, rather than printing all output in a column

def playerchoice(XO):
    p = input(f'Player 1 place an {XO} (level, row, column [0-indexed]):\n')
    z, r, c= map(int, p.split(','))
    return z, r, c

def computerchoice(gameboard):
    print("Computer's turn")
    # pause the execution of the code for 2 seconds
    time.sleep(2)
    # find the indices of the gameboard elements that equal ' '
    indices = np.where(gameboard == ' ')
    # select a random index from the indices
    random_index = np.random.choice(len(indices[0]))
    # get the row and column indices of the random element
    z ,r, c = indices[0][random_index], indices[1][random_index], indices[2][random_index]
    return z, r, c
    
    

def play_3dtictactoe():
    playerfirst = None
    while playerfirst == None:
        playerfirst = int(input("Who plays first? Computer(0) or you(1)?\n"))
        if playerfirst not in (0, 1):
            print('Please enter either 0 (computer plays first) or 1 (you play first)\n')
            playerfirst = None
    #set up the game board:
    gameboard = np.array([' ']*64).reshape(4,4,4)
    # function to convert game board to HTML (looks nicer and each new iteration of the game board replaces the old one)
    def gameboard_to_html(gameboard):
        html = "<table style='width: 100%; height: 100%;'>"
        html += "<tr>"
        for z, level in enumerate(gameboard):
            html += "<td style='width: 10%;'>"
            html += "<table style='width: 25%; height: 100%;'>"
            for i, row in enumerate(level):
                html += "<tr>"
                for j, cell in enumerate(row):
                    if (z + i + j) % 2 == 0:
                        bgcolor = "#000000"
                    else:
                        bgcolor = "#2A2A2A"
                    html += f"<td style='background-color: {bgcolor}; width: 25%; height: 25%; text-align: center; vertical-align: middle; font-size: 1em; padding: 10%;'>{cell}</td>"
                html += "</tr>"
            html += "</table>"
            html += "</td>"
        html += "</tr>"
        html += "</table>"
        return html
    # display the game board as HTML
    display(HTML(gameboard_to_html(gameboard)))

    #set up loop until gameover
    gameover = 0
    while not gameover:
        if playerfirst == 1:
            XO = 'X'
            #player 1:
            r = None
            while r is None: #set up a while loop to repeat asking and checking for user input if it's invalid
                #Player 1 places an X
                try:
                    z, r, c = playerchoice(XO)
                    #make sure this in an empty space before placing the X
                    if gameboard[z, r,c] == ' ':
                        gameboard[z, r,c] = 'X'
                        # clear the output of the current gameboard
                        clear_output(wait=True)
                        display(HTML(gameboard_to_html(gameboard)))
                    else:
                        print("Sorry, you can't go there. Try again.")
                        r = None
                except IndexError:
                    print(f'{z, r, c} is out of range. Please try again.')
                    r = None
            #Check if the game has been won:
            Xwin = ['X', 'X', 'X', 'X']
            if (np.array_equal(gameboard[z, r,:],Xwin) or np.array_equal(gameboard[z,:,c],Xwin) or np.array_equal(gameboard[:,r,c],Xwin) or  #column, row, or z-slice
                np.array_equal(np.diag(gameboard[z]),Xwin) or np.array_equal(np.diag(np.fliplr(gameboard[z])),Xwin) or #diagonals within each z-plane
                np.array_equal(np.diag(gameboard[:,r,:]), Xwin) or np.array_equal(np.diag(np.fliplr(gameboard[:,r,:])), Xwin) or #diagonals within each row
                np.array_equal(np.diag(gameboard[:,:,c]), Xwin) or np.array_equal(np.diag(np.fliplr(gameboard[:,:,c])), Xwin) or #diagonals within each column
                #finally, true 3-d diagonals cutting through levels, rows, and cols
                np.array_equal(gameboard[(0,1,2,3), (0,1,2,3), (0,1,2,3)], Xwin) or np.array_equal(gameboard[(0,1,2,3),(0,1,2,3),(3,2,1,0)], Xwin) or 
                np.array_equal(gameboard[(0,1,2,3),(3,2,1,0),(0,1,2,3)], Xwin) or np.array_equal(gameboard[(0,1,2,3),(3,2,1,0),(3,2,1,0)], Xwin)):
                print ('X wins!!')
                gameover = 1
                break
            #Check if the game is a draw:
            if ' ' not in gameboard:
                print("It's a draw...")
                gameover = 1
                break
            #player 2:
            #Player 2 places an O
            z, r, c = computerchoice(gameboard)
            #make sure this in an empty space before placing the X
            gameboard[z,r,c] = 'O'
            # clear the output of the current cell
            clear_output(wait=True)
            display(HTML(gameboard_to_html(gameboard)))
            #Check if the game has been won:
            Owin = ['O', 'O', 'O', 'O']
            if (np.array_equal(gameboard[z, r,:],Owin) or np.array_equal(gameboard[z,:,c],Owin) or np.array_equal(gameboard[:,r,c],Owin) or  #column, row, or z-slice
                np.array_equal(np.diag(gameboard[z]),Owin) or np.array_equal(np.diag(np.fliplr(gameboard[z])),Owin) or #diagonals within each z-plane
                np.array_equal(np.diag(gameboard[:,r,:]), Owin) or np.array_equal(np.diag(np.fliplr(gameboard[:,r,:])), Owin) or #diagonals within each row
                np.array_equal(np.diag(gameboard[:,:,c]), Owin) or np.array_equal(np.diag(np.fliplr(gameboard[:,:,c])), Owin) or #diagonals within each column
                #finally, true 3-d diagonals cutting through levels, rows, and cols
                np.array_equal(gameboard[(0,1,2,3), (0,1,2,3), (0,1,2,3)], Owin) or np.array_equal(gameboard[(0,1,2,3),(0,1,2,3),(3,2,1,0)], Owin) or 
                np.array_equal(gameboard[(0,1,2,3),(3,2,1,0),(0,1,2,3)], Owin) or np.array_equal(gameboard[(0,1,2,3),(3,2,1,0),(3,2,1,0)], Owin)):
                print ('O wins!!')
                gameover = 1
                break
            #Check if the game is a draw:
            if ' ' not in gameboard:
                print("It's a draw...")
                gameover = 1
                break
        if playerfirst == 0:
            XO = 'O'
            #player 1:
            z, r, c = computerchoice(gameboard)
            gameboard[z,r,c] = 'X'
            # clear the output of the current cell
            clear_output(wait=True)
            display(HTML(gameboard_to_html(gameboard)))
            #Check if the game has been won:
            Xwin = ['X', 'X', 'X', 'X']
            if (np.array_equal(gameboard[z, r,:],Xwin) or np.array_equal(gameboard[z,:,c],Xwin) or np.array_equal(gameboard[:,r,c],Xwin) or  #column, row, or z-slice
                np.array_equal(np.diag(gameboard[z]),Xwin) or np.array_equal(np.diag(np.fliplr(gameboard[z])),Xwin) or #diagonals within each z-plane
                np.array_equal(np.diag(gameboard[:,r,:]), Xwin) or np.array_equal(np.diag(np.fliplr(gameboard[:,r,:])), Xwin) or #diagonals within each row
                np.array_equal(np.diag(gameboard[:,:,c]), Xwin) or np.array_equal(np.diag(np.fliplr(gameboard[:,:,c])), Xwin) or #diagonals within each column
                #finally, true 3-d diagonals cutting through levels, rows, and cols
                np.array_equal(gameboard[(0,1,2,3), (0,1,2,3), (0,1,2,3)], Xwin) or np.array_equal(gameboard[(0,1,2,3),(0,1,2,3),(3,2,1,0)], Xwin) or 
                np.array_equal(gameboard[(0,1,2,3),(3,2,1,0),(0,1,2,3)], Xwin) or np.array_equal(gameboard[(0,1,2,3),(3,2,1,0),(3,2,1,0)], Xwin)):
                print ('X wins!!')
                gameover = 1
                break
            #Check if the game is a draw:
            if ' ' not in gameboard:
                print("It's a draw...")
                gameover = 1
                break
            #player 2:
            r = None
            while r is None: #set up a while loop to repeat asking and checking for user input if it's invalid
                #Player 2 places an O
                try:
                    z, r, c = playerchoice(XO)
                    #make sure this in an empty space before placing the X
                    if gameboard[z,r,c] == ' ':
                        gameboard[z,r,c] = 'O'
                        # clear the output of the current cell
                        clear_output(wait=True)
                        display(HTML(gameboard_to_html(gameboard)))
                    else:
                        print("Sorry, you can't go there. Try again.")
                        r = None
                except IndexError:
                    print(f'{r, c} is out of range. Please try again.')
                    r = None
            #Check if the game has been won:
            Owin = ['O', 'O', 'O', 'O']
            if (np.array_equal(gameboard[z, r,:],Owin) or np.array_equal(gameboard[z,:,c],Owin) or np.array_equal(gameboard[:,r,c],Owin) or  #column, row, or z-slice
                np.array_equal(np.diag(gameboard[z]),Owin) or np.array_equal(np.diag(np.fliplr(gameboard[z])),Owin) or #diagonals within each z-plane
                np.array_equal(np.diag(gameboard[:,r,:]), Owin) or np.array_equal(np.diag(np.fliplr(gameboard[:,r,:])), Owin) or #diagonals within each row
                np.array_equal(np.diag(gameboard[:,:,c]), Owin) or np.array_equal(np.diag(np.fliplr(gameboard[:,:,c])), Owin) or #diagonals within each column
                #finally, true 3-d diagonals cutting through levels, rows, and cols
                np.array_equal(gameboard[(0,1,2,3), (0,1,2,3), (0,1,2,3)], Owin) or np.array_equal(gameboard[(0,1,2,3),(0,1,2,3),(3,2,1,0)], Owin) or 
                np.array_equal(gameboard[(0,1,2,3),(3,2,1,0),(0,1,2,3)], Owin) or np.array_equal(gameboard[(0,1,2,3),(3,2,1,0),(3,2,1,0)], Owin)):
                print ('O wins!!')
                gameover = 1
                break
            #Check if the game is a draw:
            if ' ' not in gameboard:
                print("It's a draw...")
                gameover = 1
                break



play_3dtictactoe()


X wins!!


In [152]:
#ex7.14 (Horizontal and Vertical Stacking) 
import numpy as np

#Create the two-dimensional arrays:
array1 = np.array([[0,1], [2,3]])
array2 = np.array([[4,5],[6,7]])

#1.Use vertical stacking to create the 4-by-2 array named array3 with array1 stacked on top of array2.
array3 = np.vstack((array1, array2))
print('array3')
print(array3)

#2. Use horizontal stacking to create the 2-by-4 array named array4 with array2 to the right of array1
array4 = np.hstack((array1, array2))
print('array4')
print(array4)

#3. Use vertical stacking with two copies of array4 to create a 4-by-4 array5
array5 = np.vstack((array4, array4))
print('array5')
print(array5)

#4. Use horizontal stacking with two copies of array3 to create a 4-by-4 array6
array6 = np.hstack((array3, array3))
print('array6')
print(array6)

array3
[[0 1]
 [2 3]
 [4 5]
 [6 7]]
array4
[[0 1 4 5]
 [2 3 6 7]]
array5
[[0 1 4 5]
 [2 3 6 7]
 [0 1 4 5]
 [2 3 6 7]]
array6
[[0 1 0 1]
 [2 3 2 3]
 [4 5 4 5]
 [6 7 6 7]]


In [156]:
#ex.7.15 Research NumPy function concatenate, then use it to reimplement the previous exercise

import numpy as np

#Create the two-dimensional arrays:
array1 = np.array([[0,1], [2,3]])
array2 = np.array([[4,5],[6,7]])

#1.create the 4-by-2 array named array3 with array1 stacked on top of array2.
array3 = np.concatenate((array1, array2), axis = 0) #axis = 0 produces vertical stack
print('array3')
print(array3)

#2. create the 2-by-4 array named array4 with array2 to the right of array1
array4 = np.concatenate((array1, array2), axis = 1) #axis = 1 produces horizontal stack
print('array4')
print(array4)

#3. Use two copies of array4 to create a 4-by-4 array5 with one on top of the other
array5 = np.concatenate((array4, array4), axis = 0)
print('array5')
print(array5)

#4. Use  two copies of array3 to create a 4-by-4 array6 side-by-side
array6 = np.concatenate((array3, array3), axis = 1)
print('array6')
print(array6)

array3
[[0 1]
 [2 3]
 [4 5]
 [6 7]]
array4
[[0 1 4 5]
 [2 3 6 7]]
array5
[[0 1 4 5]
 [2 3 6 7]
 [0 1 4 5]
 [2 3 6 7]]
array6
[[0 1 0 1]
 [2 3 2 3]
 [4 5 4 5]
 [6 7 6 7]]


In [173]:
#ex7.16 Research and use NumPy’s tile function to create a checkerboard pattern of dashes and asterisks

a = np.array([['*','-'], ['-','*']])
a1 = np.tile(a, (8,8))

for row in range(a1.shape[0]):
    for element in range(a1.shape[1]):
        print(a1[row, element], end = '  ')
    print()

*  -  *  -  *  -  *  -  *  -  *  -  *  -  *  -  
-  *  -  *  -  *  -  *  -  *  -  *  -  *  -  *  
*  -  *  -  *  -  *  -  *  -  *  -  *  -  *  -  
-  *  -  *  -  *  -  *  -  *  -  *  -  *  -  *  
*  -  *  -  *  -  *  -  *  -  *  -  *  -  *  -  
-  *  -  *  -  *  -  *  -  *  -  *  -  *  -  *  
*  -  *  -  *  -  *  -  *  -  *  -  *  -  *  -  
-  *  -  *  -  *  -  *  -  *  -  *  -  *  -  *  
*  -  *  -  *  -  *  -  *  -  *  -  *  -  *  -  
-  *  -  *  -  *  -  *  -  *  -  *  -  *  -  *  
*  -  *  -  *  -  *  -  *  -  *  -  *  -  *  -  
-  *  -  *  -  *  -  *  -  *  -  *  -  *  -  *  
*  -  *  -  *  -  *  -  *  -  *  -  *  -  *  -  
-  *  -  *  -  *  -  *  -  *  -  *  -  *  -  *  
*  -  *  -  *  -  *  -  *  -  *  -  *  -  *  -  
-  *  -  *  -  *  -  *  -  *  -  *  -  *  -  *  


In [178]:
#ex7.17 Research and use the NumPy bincount function to count the number of occurrences 
# of each non-negative integer in a 5-by-5 array of random integers in the range 0–99
import numpy as np

a = np.array([np.random.randint(0, 100, size = 25)]).reshape(5, 5)
print(a)

np.bincount(a.flatten())

[[58 20 34 28 30]
 [40 18  9 59 86]
 [31 41 51 73 49]
 [90 58 11 20 48]
 [68 24 45 35 90]]


array([0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 2, 0,
       0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0,
       0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 2, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 2], dtype=int64)

In [193]:
#ex7.18 (Median and Mode of an array) 
# NumPy arrays offer a mean method, but not median or mode. Write functions median and mode that use existing NumPy capabilities 
# to determine the median (middle) and mode (most frequent) of the values in an array. Your functions should determine the median 
# and mode regardless of the array’s shape. Test your function on three arrays of different shapes.

def np_median(a):
    x = sorted(a.flatten())
    mid = len(x)//2
    #if x has an odd number of elements:
    if len(x)%2 !=0:
        median = x[mid]
    #if x has an even number of elements:
    else:
        median = (x[mid] + x[mid-1])/2
    return median

print(np_median(np.array([0, 1, 2, 3])))

print(np_median(np.array([0, 1, 2])))

print(np_median(np.arange(6).reshape(2, 3)))


def np_mode(a):
    x = np.bincount(a.flatten())
    xx = np.where(x==max(x))[0]
    if len(xx) == 1:
        mode = xx[0]
    else:
        mode = [xx[i] for i in range(len(xx))]
    return mode

print(np_mode(np.array([[1, 2, 1],[0,1,2],[2,3,4]])))


1.5
1
2.5
[1, 2]


In [209]:
#ex7.19 (Enhanced Median and Mode of an array) 
# Modify your functions from the previous exercise to allow the user to provide an axis keyword argument so the 
# calculations can be performed row-by-row or column-by-column on a two-dimensional array

def np_median(a, axis=0):
    medians = []
    for i in range(a.shape[axis]):
        if axis == 1:
            x = sorted(a[:,i])
        else:
            x = sorted(a[i])
        mid = len(x)//2
        #if x has an odd number of elements:
        if len(x)%2 !=0:
            median = x[mid]
        #if x has an even number of elements:
        else:
            median = (x[mid] + x[mid-1])/2
        medians.append(median)
    return(medians)


x = np.array(np.random.randint(1, 5, size = 16)).reshape(4, 4)
print(x)
print(np_median(x, axis = 0))
print(np_median(x, axis = 1))


def np_mode(a, axis = 0):
    modes = []
    for i in range(a.shape[axis]):
        if axis == 1:
            x = np.bincount(a[:,i])
        else:
            x = np.bincount(a[i])
        xx = np.where(x == max(x))[0]
        if len(xx) == 1:
            mode = xx[0]
        else:
            mode = [xx[i] for i in range(len(xx))]
        modes.append(mode)
    return(modes)

print(np_mode(x, axis = 0))
print(np_mode(x, axis = 1))

[[2 3 2 3]
 [3 3 2 3]
 [4 4 3 1]
 [4 4 2 4]]
[2.5, 3.0, 3.5, 4.0]
[3.5, 3.5, 2.0, 3.0]
[[2, 3], 3, 4, 4]
[4, [3, 4], 2, 3]


In [223]:
#ex7.20 (Performance Analysis) 
# In this chapter, we used %timeit to compare the average execution times of generating a list of 6,000,000 random die rolls vs. generating an array of 6,000,000 random die rolls. 
# Though we saw approximately two orders of magnitude performance improvement with array, we generated the list and the array using two different random-number generators 
# and different techniques for building each collection. If you use the same techniques we showed to generate a one-element list and a one-element array, creating the list is slightly faster. 
# Repeat the %timeit operations for one-element collections. Then do it again for 10, 100, 1000, 10,000, 100,000, and 1,000,000 elements and compare the results on your system. 

import numpy as np
import random

for i in (1,10, 100, 1000, 10_000, 100_000, 1_000_000):
    print(f'{i} value(s):')
    print('List')
    %timeit [random.randrange(1, 7) for reps in range(i)]
    print('Array')
    %timeit np.random.randint(1, 7, size = i)
    


1 value(s):
List
2.77 µs ± 328 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)
Array
21.6 µs ± 869 ns per loop (mean ± std. dev. of 7 runs, 10,000 loops each)
10 value(s):
List
20.6 µs ± 3.86 µs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)
Array
19 µs ± 1.56 µs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)
100 value(s):
List
189 µs ± 24.9 µs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)
Array
20.1 µs ± 1.66 µs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)
1000 value(s):
List
1.91 ms ± 189 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)
Array
37 µs ± 2.48 µs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)
10000 value(s):
List
18.4 ms ± 1 ms per loop (mean ± std. dev. of 7 runs, 100 loops each)
Array
200 µs ± 13.8 µs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)
100000 value(s):
List
180 ms ± 11.3 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
Array
1.91 ms ± 192 µs per loop (mean ± std. dev

In [231]:
#ex7.22(Pandas: Series) Perform the following tasks with pandas Series:
import pandas as pd

# Create a Series from the list [7, 11, 13, 17]
pd.Series([7, 11, 13, 17])

# Create a Series with five elements that are all 100.0
pd.Series([100]*5)

# Create a Series with 20 elements that are all random numbers in the range 0 to 100. Use method describe to produce the Series’ basic descriptive statistic
pd.Series(np.random.randint(0, 101, size = 20)).describe()

# Create a Series called temperatures of the floating-point values 98.6, 98.9, 100.2 and 97.9. Using the index keyword argument, specify the custom indices 'Julie', 'Charlie', 'Sam' and 'Andrea'.
temperatures = pd.Series([98.6, 98.9, 100.2, 97.9], index = ('Julie', 'Charlie', 'Sam', 'Andrea'))
temperatures

# Form a dictionary from the names and values in Part (d), then use it to initialize a Series
temp_dict = {'Julie': 98.6, 'Charlie': 98.9, 'Sam': 100.2, 'Andrea': 97.9}
temps = pd.Series(temp_dict)
temps

Julie       98.6
Charlie     98.9
Sam        100.2
Andrea      97.9
dtype: float64

In [269]:
#ex7.23 (Pandas: DataFrames) Perform the following tasks with pandas DataFrames:

import pandas as pd

#1 Create a DataFrame named temperatures from a dictionary of three temperature readings each for 'Maxine', 'James' and 'Amanda'
temps_dic = {'Maxine':[36.5, 36.8, 37.0], 'James':[37.1, 36.9, 37.2], 'Amanda':[36.7, 36.5, 36.4]}
temps = pd.DataFrame(temps_dic)
temps

#2 Recreate the DataFrame temperatures in Part (a) with custom indices using the index keyword argument and a list containing 'Morning', 'Afternoon' and 'Evening'
temps = pd.DataFrame(temps_dic, index = ['Morning', 'Afternoon', 'Evening'])
temps

#3 Select from temperatures the column of temperature readings for 'Maxine'
temps.Maxine

#4 Select from temperatures the row of 'Morning' temperature readings
temps.loc['Morning']

#5 Select from temperatures the rows for 'Morning' and 'Evening' temperat
temps.loc[['Morning', 'Evening']]

#6 Select from temperatures the columns of temperature readings for 'Amanda' and 'Maxine'
temps.loc[:, ['Amanda', 'Maxine']]

#7 Select from temperatures the elements for 'Amanda' and 'Maxine' in the 'Morning' and 'Afternoon'
temps.loc[['Morning','Afternoon'], ['Amanda', 'Maxine']]

#8 Use the describe method to produce temperatures’ descriptive statistics.
temps.describe()

#9 Transpose temperatures
temps.T

#10 Sort temperatures so that its column names are in alphabetical order
temps.sort_index(axis = 1)


Amanda  James  Maxine
Morning      36.7   37.1    36.5
Afternoon    36.5   36.9    36.8
Evening      36.4   37.2    37.0

In [13]:
#ex7.24 (AI Project: Introducing Heuristic Programming with the Knight’s Tour) 
# An interesting puzzler for chess buffs is the Knight’s Tour problem, originally proposed by the mathematician Euler. 
# Can the knight piece move around an empty chessboard and touch each of the 64 squares once and only once? We study this intriguing problem in depth here
# The knight makes only L-shaped moves (two spaces in one direction and one space in a perpendicular direction). Thus, as shown in the figure below, 
# from a square near the middle of an empty chessboard, the knight (labeled K) can make eight different moves (numbered 0 through 7)
import numpy as np
import time
import random
from IPython.display import clear_output

#let’s develop a script that will move the knight around a chessboard represented by an eight-by-eight two-dimensional array named board. 
#Initialize each square to zero. 
board = np.array([0]*64).reshape(8, 8)

# We describe each of the eight possible moves in terms of its horizontal and vertical components. 
# For example, a move of type 0, as shown in the preceding figure, consists of moving two squares horizontally to the right and one square vertically upward. 
# A move of type 2 consists of moving one square horizontally to the left and two squares vertically upward. Horizontal moves to the left and 
# vertical moves upward are indicated with negative numbers. The eight moves may be described by two one-dimensional arrays, horizontal and vertical, as follow
horizontal = np.array([2,1,-1,-2,-2,-1,1,2])
vertical = np.array([-1,-2,-2,-1,1,2,2,1])

# Let the variables current_row and current_column indicate the row and column, respectively, of the knight’s current position. 
# To make a move of type move_number (a value 0–7), your script should use the statement
# current_row += vertical[move_number]
# current_column += horizontal[move_number]

# Write a script to move the knight around the chessboard. 
# Keep a counter that varies from 1 to 64. Record the latest count in each square the knight moves to. 
# Test each potential move to see if the knight has already visited that square. Test every potential move to ensure that the knight does not land off the chessboard. 
# Run the application. How many moves did the knight make?
# current_row = random.randint(0,7)
# current_column = random.randint(0,7)
# counter = 1
# while counter < 65:
#     board[current_row, current_column] = counter
#     #time.sleep(1)
#     clear_output()
#     print(board)
#     moves = []
#     for i in range(len(horizontal)):
#         try:
#             if current_row + vertical[i]>=0 and current_column + horizontal[i]>=0 and board[current_row + vertical[i], current_column + horizontal[i]] == 0:
#                 moves.append(i)
#         except IndexError:
#             pass
#     #select a possible move at random:
#     if len(moves)>0:
#         move = random.choice(moves)
#         current_row += vertical[move]
#         current_column += horizontal[move]
#         counter += 1
#     else:
#         print(f'No more possible moves. Stopping on move {counter}.')
#         counter = 65

            

# Write a new version of the Knight’s Tour, using the accessibility heuristic. The knight should always move to the square with the lowest accessibility number. 
# In case of a tie, the knight may move to any of the tied squares. Therefore, the tour may begin in any of the four corners. 
accessibility = np.array([[2,3,4,4,4,4,3,2],[3,4,6,6,6,6,4,3],[4,6,8,8,8,8,6,4],[3,4,6,6,6,6,4,3],[2,3,4,4,4,4,3,2]])
accessibility = np.repeat(accessibility, repeats = [1,1,4,1,1], axis = 0)

#choose a random start location based on lowest accessibility (i.e. a corner)
start_rows, start_cols = np.where(accessibility == accessibility.min())
start_i = random.randint(0, len(start_rows)-1)

current_row = start_rows[start_i]
current_column = start_cols[start_i]
counter = 1
while counter < 65:
    board[current_row, current_column] = counter
    time.sleep(1)
    clear_output()
    print(board)
    #find possible moves (unoccupied spaces, within the game board area)
    moves = []
    access = []
    for i in range(len(horizontal)):
        try:
            if current_row + vertical[i]>=0 and current_column + horizontal[i]>=0 and board[current_row + vertical[i], current_column + horizontal[i]] == 0:
                moves.append(i)
                access.append(accessibility[current_row + vertical[i], current_column + horizontal[i]])
        except IndexError:
            pass
    #select a possible move based on lowest accessibility:
    access = np.array(access)
    if len(moves)>0:
        bestmove = random.choice(np.where(access == access.min())[0])
        move = moves[bestmove]
        current_row += vertical[move]
        current_column += horizontal[move]
        counter += 1
    else:
        print(f'No more possible moves. Stopping on move {counter}.')
        counter = 65


[[ 1 46  3 18 49 44 13 16]
 [ 4 19 48 45 14 17 28 43]
 [47  2 55 50  0 52 15 12]
 [20  5  0 53 58 27 42 29]
 [35 54 59 56 51  0 11 26]
 [ 6 21 36  0 60 57 30 41]
 [37 34 23  8 39 32 25 10]
 [22  7 38 33 24  9 40 31]]
No more possible moves. Stopping on move 60.


In [50]:
#ex7.24 contd: Modify the script to run 64 tours, one starting from each square of the chessboard. How many full tours did you get
#ex7.26 (Closed-Tour test)
# A closed tour occurs when the 64th move is one move away from the square in which the knight started the tour. 
# Modify the script you wrote in Exercise 7.24 to test for a closed tour if a full tour has occurred.

import numpy as np
import time
import random
from IPython.display import clear_output

def knights_tour(start = [0, 0]):
    #Initialize each square to zero. 
    board = np.array([0]*64).reshape(8, 8)

    # We describe each of the eight possible moves in terms of its horizontal and vertical components. 
    # For example, a move of type 0, as shown in the preceding figure, consists of moving two squares horizontally to the right and one square vertically upward. 
    # A move of type 2 consists of moving one square horizontally to the left and two squares vertically upward. Horizontal moves to the left and 
    # vertical moves upward are indicated with negative numbers. The eight moves may be described by two one-dimensional arrays, horizontal and vertical, as follow
    horizontal = np.array([2,1,-1,-2,-2,-1,1,2])
    vertical = np.array([-1,-2,-2,-1,1,2,2,1])

    # Write a new version of the Knight’s Tour, using the accessibility heuristic. The knight should always move to the square with the lowest accessibility number. 
    # In case of a tie, the knight may move to any of the tied squares. Therefore, the tour may begin in any of the four corners. 
    accessibility = np.array([[2,3,4,4,4,4,3,2],[3,4,6,6,6,6,4,3],[4,6,8,8,8,8,6,4],[3,4,6,6,6,6,4,3],[2,3,4,4,4,4,3,2]])
    accessibility = np.repeat(accessibility, repeats = [1,1,4,1,1], axis = 0)

    current_row = start[0]
    current_column = start[1]
    counter = 1
    while counter < 65:
        board[current_row, current_column] = counter
        #time.sleep(1)
        #clear_output()
        #print(board)
        #find possible moves (unoccupied spaces, within the game board area)
        moves = []
        access = []
        for i in range(len(horizontal)):
            try:
                if current_row + vertical[i]>=0 and current_column + horizontal[i]>=0 and board[current_row + vertical[i], current_column + horizontal[i]] == 0:
                    moves.append(i)
                    access.append(accessibility[current_row + vertical[i], current_column + horizontal[i]])
            except IndexError:
                pass
        #select a possible move based on lowest accessibility:
        access = np.array(access)
        if len(moves)>0:
            bestmove = random.choice(np.where(access == access.min())[0])
            move = moves[bestmove]
            current_row += vertical[move]
            current_column += horizontal[move]
            counter += 1
        else:
            endcounter = counter
            counter = 65
            #check if a possible move leads back to 1:
            closedtour = 0
            for i in range(len(horizontal)):
                try:
                    if endcounter == 64 and current_row + vertical[i]>=0 and current_column + horizontal[i]>=0 and board[current_row + vertical[i], current_column + horizontal[i]] == 1:
                        closedtour = 1
                except IndexError:
                    pass
            return endcounter, closedtour

results = []
closedtours = []
for r in range(8):
    for c in range(8):    
        result, closed = knights_tour([r,c])  
        results.append(result)
        closedtours.append(closed)

fulltours = results.count(64)

print(f'There were {fulltours} completed Knights Tours.')

counts = np.bincount(np.array(results))
moves = np.arange(65)

print('Game ends:')
print('moves  n_games')
for i in range(len(moves)):
    if counts[i] > 0:
        print(f'{moves[i]:>5}{counts[i]:>9}')

#was there a closed tour?
print(f'Number of closed tours: {sum(closedtours)}')



        

There were 8 completed Knights Tours.
Game ends:
moves  n_games
   50        1
   51        1
   52        1
   54        3
   55        2
   56        7
   58        7
   59        2
   60       13
   61        2
   62       11
   63        6
   64        8
Number of closed tours: 1
